version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - bookstore-network
      
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: umis1
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - bookstore-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123qwe
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - bookstore-network
    restart: unless-stopped

networks:
  bookstore-network:

volumes:
    postgres:
    pgadmin: